### ISSUE TITLE
WARNING: You do not have /usr/local/bin/slack/slack.sh symlinked.

### ISSUE THREAD

**Issue by gonace** [openbridge/ob_hacky_slack#4]
So I downloaded the script to /usr/local/bin/slack/slack.sh and created a symlink in /usr/bin to that file but when I run it I get:

```

WARNING: You do not have /usr/local/bin/slack/slack.sh symlinked.
ln: failed to create hard link '/usr/bin/slack': File exists

```

Also the ip.txt could not be created so I was forced to manually create that file.

**Comment by tspicer** [comment]
What OS are you using?

**Comment by gonace** [comment]
I'm using Debian GNU/Linux 8.5 (jessie) (3.16.0-4-amd64).

**Comment by gonace** [comment]
I also tried to send the example message that was provided in the documentation and it seams that no argument is working:

```
payway@payway-linux01:/usr/local/bin$ slack -k "*" -c "#payway" -u "hacky-slack" -i "apple" -a "Macbook" -b "http://www.apple.com/" -t "Where are the new 2016 Macbook models?"
INFO: No Slack API WEBHOOK endpoint was set as a system variable or passed (-w). Defaulting to generic Slack WEBHOOK to POST messages...

ERROR: No Slack API TOKEN was found. Can not proceed with posting messages to the API without one. Make sure you pass one via the command line (-k yourtoken)
WARNING: You do not have /usr/local/bin/slack/slack.sh symlinked.
ln: failed to access '/usr/local/bin/slack/slack.sh': No such file or directory
/tmp/ip.txt is less than 2 hours old.
/tmp/ip.txt: line 1: 10.2.0.4: command not found
WARNING: You do not have any TEXT (-t) specified in the message.
WARNING: You do not have a TITLE (-T) specified for the message.
WARNING: You do not have a PRETEXT (-p) specified for the message.
WARNING: A CHANNEL (-c) was not set. Using the default CHANNEL...
INFO: STATUS (-s) was not set. Setting a default STATUS to INFO...
ERROR: The POST to the Slack API failed

```

Although this message is actually being sent to Slack.

**Comment by tspicer** [comment]
How are you passing the token? Do you have the token embedded into the script?

This error means it is having trouble locating the token:
`ERROR: No Slack API TOKEN was found. Can not proceed with posting messages to the API without one. Make sure you pass one via the command line (-k yourtoken)`

**Comment by gonace** [comment]
I'm using `-k "token"` from a shell just for testing.

I'm a bit confused over the installation steps, it says to download the script into /usr/local/bin but the script then warns about that the symlink for "/usr/local/bin/slack/slack.sh" is not there.

And the "tmp/ip.txt does not exist" warning is never explained, should one create that file by once self?

**Comment by tspicer** [comment]
Hmm, let me re-run some tests. I might have overlooked something in my local config and did not properly set it up or document it. I'm driving some place now, but will take a look as soon as I get to the office. Thanks for the feedback!

**Comment by gonace** [comment]
Awesome, thanks for the fast replies if there is anything more you need from me to perform the test just give me a shout here. 

Regards

**Comment by gonace** [comment]
This might be of value (?):

```
carma-stage@payway-linux01:~/log$ /usr/bin/bash -c 'sh /usr/local/bin/slack.sh -k "**REMOVED**" -a -c "#payway-monitoring" -i ":slack:" -T "Titles are awesome" -p "Pretext is so helpful to include" -s error'
/usr/local/bin/slack.sh: 8: /usr/local/bin/slack.sh: [[: not found
/usr/local/bin/slack.sh: 11: /usr/local/bin/slack.sh: [[: not found
INFO: No Slack API WEBHOOK endpoint was set as a system variable or passed (-w). Defaulting to generic Slack WEBHOOK to POST messages...

/usr/local/bin/slack.sh: 21: /usr/local/bin/slack.sh: [[: not found
/usr/local/bin/slack.sh: 23: /usr/local/bin/slack.sh: [[: not found
ERROR: No Slack API TOKEN was found. Can not proceed with posting messages to the API without one. Make sure you pass one via the command line (-k yourtoken)
WARNING: You do not have /usr/local/bin/slack/slack.sh symlinked.
ln: failed to create hard link '/usr/bin/slack': File exists
/usr/local/bin/slack.sh: 48: /usr/local/bin/slack.sh: [[: not found
/tmp/ip.txt is less than 2 hours old.
/usr/local/bin/slack.sh: 61: /usr/local/bin/slack.sh: source: not found
/usr/local/bin/slack.sh: 67: /usr/local/bin/slack.sh: Syntax error: "(" unexpected
```

**Comment by tspicer** [comment]
Ok, I know the issue.

If you manually put the token into slack.sh like this (use your token)

`SLACK_TOKEN="310-3910-93-01932-01923-0kjdkladjalkjdyTAR"`

Then  run it like this:

`sh -x slack.sh -c "#general" -u "hacky-slack" -i "apple" -a "Macbook" -b "http://www.apple.com/" -t "Where are the new 2016 Macbook models"`

Everything is happy. 

The -x will print all the activity for testing. 

So it looks like passing the token via -k is the issue. I will fix that and then post an update.

**Comment by tspicer** [comment]
Can you test the develop branch?
https://github.com/openbridge/ob_hacky_slack/tree/develop

**Comment by gonace** [comment]
Sorry was not able to access github since the DDoS I'll try it later today.

Regards

**Comment by gonace** [comment]
Mange to get a few minutes to test it anyway:

```
payway@payway-linux01:/usr/local/bin$ sh -x slack.sh -k "**MASKED**" -a -c "#payway-monitoring" -i ":slack:" -T "Titles are awesome" -p "Pretext is so helpful to include" -s error
+ [[ -n ]]
slack.sh: 8: slack.sh: [[: not found
+ [[ -n ]]
slack.sh: 12: slack.sh: [[: not found
+ echo INFO: Using default Slack API endpoint to POST messages...
INFO: Using default Slack API endpoint to POST messages...
+ WEBHOOK=https://hooks.slack.com/services/
+ date +%Y%m%d
+ DATE=20161022
+ hostname -s
+ HOSTNAME=payway-linux01
+ CONFIG=/etc/slack.d
+ IPCONFIG=/tmp/ip.txt
+ APP=/usr/local/bin/slack.sh
+ BIN=/usr/bin/slack
+ test -L /usr/local/bin/slack.sh
+ echo WARNING: You do not have /usr/local/bin/slack.sh symlinked.
WARNING: You do not have /usr/local/bin/slack.sh symlinked.
+ ln /usr/local/bin/slack.sh /usr/bin/slack
ln: failed to create hard link '/usr/bin/slack': File exists
+ test  = OK
+ [[ ! -f /tmp/ip.txt ]]
slack.sh: 42: slack.sh: [[: not found
+ test find '/tmp/ip.txt' -mmin +120
+ echo /tmp/ip.txt is less than 2 hours old.
/tmp/ip.txt is less than 2 hours old.
+ source /tmp/ip.txt
slack.sh: 62: slack.sh: source: not found
slack.sh: 68: slack.sh: Syntax error: "(" unexpected

```

The script is inside "/usr/local/bin/" with the name slack.sh and /usr/bin is  symlink "/usr/bin/slack -> /usr/local/bin/slack.sh" to that file.

**Comment by gonace** [comment]
It seams to be a bash problem in debian, and that /bin/sh is really dash

```
payway@payway-linux01:/usr/local/bin$ sudo ls -l `which sh`
lrwxrwxrwx 1 root root 4 Nov  8  2014 /bin/sh -> dash
payway@payway-linux01:/usr/local/bin$ sudo ls -l `which bash`
lrwxrwxrwx 1 root root 9 Oct 21 14:27 /usr/bin/bash -> /bin/bash
```

**Comment by tspicer** [comment]
Looks like it could not create the IP file or there was an issue with the path.  I might remove that cache if it is giving you an issue

**Comment by gonace** [comment]
I reconfigured Debian (https://wiki.debian.org/DashAsBinSh) to use bash instead of dash and that fixed some of the errors with "[[", I also added the token as an environment variable.

But the passing of arguments to the script is not working still:

```
payway@payway-linux01:/usr/local/bin$ sh slack.sh -a -c "#payway-monitoring" -i "slack" -T "Titles are awesome" -p "Pretext is so helpful to include"
INFO: Using default Slack API endpoint to POST messages...
WARNING: You do not have /usr/local/bin/slack.sh symlinked.
ln: failed to create hard link '/usr/bin/slack': File exists
/tmp/ip.txt is less than 2 hours old.
INFO: The Slack API TOKEN was set as a system variable
INFO: A USERNAME (-u) was not specified for this POST to the Slack API. Setting a default username...
WARNING: You do not have any TEXT (-t) specified in the message.
WARNING: You do not have a TITLE (-T) specified for the message.
WARNING: You do not have a PRETEXT (-p) specified for the message.
WARNING: A CHANNEL (-c) was not set. Using the default CHANNEL...
INFO: STATUS (-s) was not set. Setting a default STATUS to INFO...
```

The weird thing is that some arguments are working, like -s "error" works just fine, others like -t, -T, -p, -c and so on are doesn't.

**Comment by tspicer** [comment]
Hmm, interesting. Let me look at that more closely. I had not seen that locally so I will need to try that in different env. What Debian version are you on?

**Comment by gonace** [comment]
I'm using "GNU/Linux 8.5 (jessie) (3.16.0-4-amd64).", I've manage to dig a bit deeper and found that the arguments might be working correctly but that the script warns me that they're not.

I supplied a few more aguments like -t, -T and -p and they are working fine apart from the script saying that they're not.

To me that makes no sense at all :).

**Comment by tspicer** [comment]
I'm going through everything top to bottom right now. There is some cleanup I need to do. I think there was an issue with "getopts" that I'm trying to sort through. I will post an update once I finish testing.

I was also thinking of using a tiny docker container to run this to eliminate any environment issues. Seems like too much overhead, but it might make things easier too.

**Comment by gonace** [comment]
Hi
Thanks for taking your time to look at the problems I'm having, a docker container might be nice :)

Regards
Erik

**Comment by tspicer** [comment]
Made some updates, still need to merge your changes. Also added a Docker container

`docker build -t slack .`
then you can run like this
`docker run -it slack /bin/bash /slack.sh -c "#general" -u "steve" -i "dog" -a "Macbook Pro" -B "http://www.apple.com/" -p "Almost" -Z "Where are the new 2016 Macbook models" -s "ok" -T "Wow" -L "https://www.apple.com" -k "token"`

Not a 100% the way I would want to be setup, but it works

**Comment by gonace** [comment]
Looks great, I'll try it out tomorrow..thanks again for all the help!

**Comment by tspicer** [comment]
I like the idea of using -e for environment, but I would prefer to leave it user defined, meaning you simply pass your variable whatever it might be that aligns with your dev/ops process. Any objections?

**Comment by gonace** [comment]
No, I think it's a good idea to do so!

**Comment by tspicer** [comment]
I'm going to close this issue for now. I think the original issue was solved. Any enhancement requests just let me know!
